-- MYSQL
CREATE TABLE users (
  id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  lastname VARCHAR(250) NOT NULL,
);

CREATE TABLE tasks (
  id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(250) NOT NULL,
  priority BOOLEAN NOT NULL,
  user_id SMALLINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO users (name, lastname) VALUES ('Leo', 'Diaz');

INSERT INTO tasks (name, description, priority, user_id) VALUES ('SCRIPT VIGENCIA', 
'TRABAJAR SCRIPT PARA MODIFICAR LOS USUARIOS - PETICION TODOS LOS USUARIOS COMO INDEFINIDOS -> SOLO A USUARIOS QUE NO SEAN GLOBALES', true, 1);

INSERT INTO tasks (name, description, priority, user_id) VALUES ('PERFIL GLOBAL', 'USUARIOS ADMINISTRADORES O PERFIL GLOBAL -SE DEBE DESAPARECER FORULARIO DE SI ES INDEFINIDO O NO.', false, 1);